config/routes.rb
Rails.application.routes.draw do
  resources :vocabs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vocab.rb
class Vocab < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vocabs_controller.rb
class VocabsController < ApplicationController
  before_action :set_vocab, only: [:show, :edit, :update, :destroy]

  # GET /vocabs
  # GET /vocabs.json
  def index
    @vocabs = Vocab.all
  end

  # GET /vocabs/1
  # GET /vocabs/1.json
  def show
  end

  # GET /vocabs/new
  def new
    @vocab = Vocab.new
  end

  # GET /vocabs/1/edit
  def edit
  end

  # POST /vocabs
  # POST /vocabs.json
  def create
    @vocab = Vocab.new(vocab_params)

    respond_to do |format|
      if @vocab.save
        format.html { redirect_to @vocab, notice: 'Vocab was successfully created.' }
        format.json { render :show, status: :created, location: @vocab }
      else
        format.html { render :new }
        format.json { render json: @vocab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vocabs/1
  # PATCH/PUT /vocabs/1.json
  def update
    respond_to do |format|
      if @vocab.update(vocab_params)
        format.html { redirect_to @vocab, notice: 'Vocab was successfully updated.' }
        format.json { render :show, status: :ok, location: @vocab }
      else
        format.html { render :edit }
        format.json { render json: @vocab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vocabs/1
  # DELETE /vocabs/1.json
  def destroy
    @vocab.destroy
    respond_to do |format|
      format.html { redirect_to vocabs_url, notice: 'Vocab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vocab
      @vocab = Vocab.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vocab_params
      params.require(:vocab).permit(:name, :def, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vocabs_helper.rb
module VocabsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VocabApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vocabs/_form.html.erb
<%= form_with(model: vocab, local: true) do |form| %>
  <% if vocab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vocab.errors.count, "error") %> prohibited this vocab from being saved:</h2>

      <ul>
      <% vocab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :def %>
    <%= form.text_field :def %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vocabs/edit.html.erb
<h1>Editing Vocab</h1>

<%= render 'form', vocab: @vocab %>

<%= link_to 'Show', @vocab %> |
<%= link_to 'Back', vocabs_path %>

app/views/vocabs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vocabs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Def</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vocabs.each do |vocab| %>
      <tr>
        <td><%= vocab.name %></td>
        <td><%= vocab.def %></td>
        <td><%= vocab.category %></td>
        <td><%= link_to 'Show', vocab %></td>
        <td><%= link_to 'Edit', edit_vocab_path(vocab) %></td>
        <td><%= link_to 'Destroy', vocab, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vocab', new_vocab_path %>

app/views/vocabs/new.html.erb
<h1>New Vocab</h1>

<%= render 'form', vocab: @vocab %>

<%= link_to 'Back', vocabs_path %>

app/views/vocabs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vocab.name %>
</p>

<p>
  <strong>Def:</strong>
  <%= @vocab.def %>
</p>

<p>
  <strong>Category:</strong>
  <%= @vocab.category %>
</p>

<%= link_to 'Edit', edit_vocab_path(@vocab) %> |
<%= link_to 'Back', vocabs_path %>